eureka:
 client:
  register-with-eureka: true
  fetch-registry: true
  serviceUrl:
    defaultZone: http://localhost:8761/eureka
  instance:
   hostname: localhost
  
server:
  port: 6071


spring:
 application:
   name: praveenoruganti-salesorder-service
 jpa:
  database: MYSQL
  show-sql: true
  generate-ddl: false
  
 datasource:
    type: com.zaxxer.hikari.HikariDataSource
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://root:password@localhost:3306/omssalesorderdb?reconnect=true
    username: root
    password: password
    hikari:
      connectionTimeout : 30000
      idleTimeout : 600000
      maxLifetime : 1800000
      maximumPoolSize : 5

 rabbitmq:
    host: localhost
    port: 5672
    username: guest
    password: guest
    
 cloud:
  stream:
   default: 
    contentType: application/json
   bindings:
     customerCreatedChannel:
       destination: CustomerCreatedExchange
       group: CustomerCreatedMQ
         
SalesOrderService:
    ItemServiceURL: http://praveenoruganti-item-service/itemservice/items/

app:
 disable:
  tryOutOption:false 
apidocs:
  info:
   description: |
   
       Sales Order Service API 
       1. Sales order customer- event subscription
          a. When a "Customer Created" event is published, sales order service needs to 
             subscribe to it. Fetch the customer details(customer id,email,first_name,last_name) 
             and insert into the local customer table
       2. Create Order- create an order and return an order id
         http://localhost:6071/salesorderservice/orders
         Input- Order Description, Order Date, customer id, list of item names
         Output- Order Id
         a. validate customer by verifying the table "customer_sos" with cust_id
         b. validate the items by calling item service with item name
            http://localhost:6072/itemservice/items/{itemname}
         c. create order by inserting the order details in  order table and items 
            for the order details in order_line_item table     
       
   version: '1.0'
   title: Sales Order Service API
   termsOfService: 'urn:tos'
   contact:
     name: Praveen Oruganti
     url: https://praveenorugantitech.blogspot.com
     email: praveenorugantitech@gmail.com  
  
