eureka:
 client:
  register-with-eureka: true
  fetch-registry: true
  serviceUrl:
    defaultZone: http://localhost:8761/eureka
  instance:
   hostname: localhost
  
server:
  port: 6072

spring:
 application:
   name: praveenoruganti-item-service
 jpa:
  database: MYSQL
  show-sql: true
  generate-ddl: false
  
 datasource:
    type: com.zaxxer.hikari.HikariDataSource
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://root:password@localhost:3306/omsitemdb?reconnect=true
    username: root
    password: password
    hikari:
      connectionTimeout : 30000
      idleTimeout : 600000
      maxLifetime : 1800000
      maximumPoolSize : 5

app:
 disable:
  tryOutOption:false 
apidocs:
  info:
   description: |
   
       Item Service API 
       1. Get items - return all the items details in the table
          http://localhost:6072/itemservice/items
       2. Get item detail if item name is sent as a parameter
        http://localhost:6072/itemservice/items/{itemname}        
       
   version: '1.0'
   title: Item Service API
   termsOfService: 'urn:tos'
   contact:
     name: Praveen Oruganti
     url: https://praveenorugantitech.blogspot.com
     email: praveenorugantitech@gmail.com  
  