spring:
  datasource:
    url: jdbc:mysql://root:password@localhost:3306/praveendb?reconnect=true
    driverClassName: com.mysql.cj.jdbc.Driver
    username: root
    password: password
  jpa:
   database-platform: org.hibernate.dialect.MySQLDialect
   show-sql: true
   hibernate:
      ddl-auto: none
      format-sql: true
   
server:
  port: 9100



